version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=bluebank
      - PGDATA=/data
    ports:
      - "5432:5432"

    volumes:
      - ~/.postgresql:/var/lib/postgresql/data